language: python

python:
  - 3.6

notifications:
  email:
    on_success: change
    on_failure: change

install:
  - pip install pycodestyle

script:
  - pycodestyle --count --show-source --exclude=ve/ ./
  - python -m unittest discover -s source/tests -p 'test_*.py' --verbose
